pkg <- asNamespace("CopulaOne")
fn <- function(name) get(name,pkg)
near <- function(x,y,tol=1e-8) stopifnot(isTRUE(all.equal(x,y,tolerance=tol)))
fails <- function(expr) stopifnot(inherits(tryCatch({force(expr); NULL},error=identity),"error"))
u <- rep(c(1e-12,.01,.2,.8,1-1e-12),5)
v <- rep(c(1e-12,.01,.2,.8,1-1e-12),each=5)
for (eta in c(-1,0,.5,.95,.99)) for (theta in c(-1,0,.5,.95,.99))
  stopifnot(all(is.finite(fn("logdFRA1_COP")(u,v,eta,theta))))
near(fn("logdFRA1_COP")(u,v,-1,-1),rep(0,length(u)),1e-8)
near(fn("pFRA1_COP")(c(0,.4,1),c(.4,1,.4),.3,.4),c(0,.4,.4))
fails(fn("dFRA1_COP")(-.1,1.5,-1,-1))
fails(fn("dFRA1_COP")(0,.5,.3,.4))
fails(fn("pFRA1_COP")(.2,.3,.3,.4,eps=-1))
near(fn("dFRA1_COP")(1e-12,1e-12,.5,.2),fn("dFRA1_COP")(1e-12,1e-12,.5,.2,eps=1e-13))
stopifnot(fn("dFRA1_COP")(1e-12,1e-12,.5,.2) > 1000*fn("dFRA1_COP")(1e-12,1e-12,.5,.2,eps=1e-8))
for (eta in c(-1,0,.5,.95)) for (theta in c(-1,0,.5,.95)) {
  C<-function(u,v) fn("pFRA1_COP")(u,v,eta,theta)
  h<-1e-5
  mixed<-(C(.3+h,.4+h)-C(.3+h,.4-h)-C(.3-h,.4+h)+C(.3-h,.4-h))/(4*h*h)
  near(fn("dFRA1_COP")(.3,.4,eta,theta),mixed,1e-4)
  p<-c(.1,.5,.9); q<-fn("C2invFRA1_COP")(p,.4,eta,theta)
  near(fn("C2FRA1_COP")(q,.4,eta,theta),p,1e-7)
}
near(fn("C2invFRA1_COP")(c(0,1),.4,.3,.4),c(0,1))
near(fn("KFRA1_COP")(c(0,1),.3,.4),c(0,1))
fails(fn("dependenceFRA1_COP")(.2,.3,quadrature_rule=list()))
near(unname(fn("dependenceFRA1_COP")(-1,-1)),rep(0,4),1e-5)
near(fn("pPP")(-.5,2,2),0); near(fn("dPP")(-.5,2,2),0)
near(fn("pPPPP")(0,1,1,2,2,log=TRUE),-Inf)
near(fn("dPPPP")(0,2,2,3,3),0)
probs<-c(0,.01,.2,.8,.99,1)
near(fn("pPP")(fn("qPP")(probs,.3,2),.3,2),probs)
for (family in c("GGEE","PPPP")) {
  pars<-if(family=="GGEE") list(al=1,be=1) else list(al=1,be=1,a=2,b=2)
  q<-do.call(fn(paste0("q",family)),c(list(u=probs),pars))
  stopifnot(q[1]==0,q[length(q)]==Inf)
  cdf<-vapply(q,function(x) do.call(fn(paste0("p",family)),c(list(x=x),pars)),numeric(1))
  near(cdf,probs,1e-7)
  fails(do.call(fn(paste0("q",family)),c(list(u=.9,maxit=0),pars)))
  fails(do.call(fn(paste0("d",family,"_COP")),c(list(u=.3,v=-.1),pars)))
}
fails(fn("qPPPP")(.99,1,1,2,2,maxit=1))
near(fn("pGGGG")(Inf,1,1,1,1,n_nodes=8),1)
fails(fn("rGGGG_COP")(1,0,1,1,1))
stopifnot(all(is.finite(fn(".log_gamma_draw")(100,1e-5))))
fails(fn("gauss_legendre_01")(1))
near(fn(".checked_cubature")(function(x) 1,lowerLimit=c(0,0),upperLimit=c(1,1))$integral,1)
fails(fn(".checked_cubature")(function(x) stop("bad integrand"),lowerLimit=c(0,0),upperLimit=c(1,1)))
dat<-cbind(c(.2,.3,.7,.8),c(.3,.6,.8,.7)); fit<-fn("fitCopulaOne")
for(opt in c("L-BFGS-B","nlm")) {
  z<-fit(c(1,1,1,1),patternpar=c(7,7,0,0),dat=dat,lower=1,upper=1,copula_family="PPPP",opt=opt)
  near(unname(z$fullpar),rep(1,4))
  z2<-fit(c(1,1,1,1),patternpar=c(0,0,0,0),dat=dat,copula_family="PPPP",opt=opt,workers=2)
  near(z$value,z2$value)
}
fails(fit(dat=dat,opt="unknown")); fails(fit(dat=dat,workers=0))
fails(fit(c(1,1),patternpar=c(1,NA),dat=dat,copula_family="GGEE"))
near(fn("tauGGEE_COP")(1,1),1/3,1e-6)
sample <- fn("rPPPP_COP")(30,.6,.6,1,1,seed=5)
initial <- -sum(log(fn("dPPPP_COP")(sample[,1],sample[,2],.6,.6,1,1)))
estimates <- numeric(0)
for(opt in c("L-BFGS-B","nlm")) {
  z <- fit(c(.6,.6,1,1),patternpar=c(7,7,0,0),dat=sample,
           copula_family="PPPP",opt=opt,se=TRUE)
  stopifnot(z$convergence==0L,z$value<=initial+1e-7,
            z$fullpar[1]==z$fullpar[2],length(z$err)==1L,
            is.finite(z$err),z$err>0,z$par>.1,z$par<5)
  estimates <- c(estimates,unname(z$par))
}
near(estimates[1],estimates[2],1e-4)
