# Run with the R version and user library intended for package development.
root <- normalizePath(getwd(), winslash="/", mustWork=TRUE)
stopifnot(file.exists(file.path(root,"DESCRIPTION")))
Sys.setenv(R_LIBS=paste(.libPaths(),collapse=.Platform$path.sep))
# Windows does not recognize the POSIX C.UTF-8 locale inherited by some shells.
if (.Platform$OS.type=="windows") Sys.setenv(LC_ALL="C",LANG="C")
work <- tempfile("CopulaOne-check-")
dir.create(work)
setwd(work)
r <- file.path(R.home("bin"),if(.Platform$OS.type=="windows") "R.exe" else "R")
status <- system2(r,c("CMD","build","--no-build-vignettes",shQuote(root)))
if(status!=0L) stop("Package build failed.")
archive <- list.files(pattern="[.]tar[.]gz$",full.names=TRUE)
stopifnot(length(archive)==1L)
status <- system2(r,c("CMD","check","--no-manual","--no-build-vignettes",shQuote(archive)))
log <- file.path(work,"CopulaOne.Rcheck","00check.log")
report <- if(file.exists(log)) readLines(log) else character()
cat(report,sep="\n")
if(status!=0L || !any(grepl("^Status: OK",report)))
  stop("Package check did not finish without errors, warnings, or notes.")
